name: Deploy Heroku

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # setup env
      - uses: actions/checkout@v2
      - name: Create env file
        env:
          PORT: 8080
          DB_URI: ${{secrets.DB_URI}}
          JWT_SECRET: ${{secrets.JWT_SECRET}}
          JWT_EXPIRES: "7d"

        run: |
          touch .env
          echo PORT=$PORT >> .env
          echo DB_URI=$DB_URI >> .env
          echo JWT_SECRET=$JWT_SECRET >> .env
          echo JWT_EXPIRES=$JWT_EXPIRES >> .env 

          echo "cat .env"
          cat .env

          echo "ls -a ."
          ls -a .

          echo "ls -a ${{ github.workspace }}"
          ls -a ${{ github.workspace }}
        shell: bash

      # deploy to heroku server
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "api-tapcart"
          heroku_email: "ryannadiputraa@gmail.com"
          usedocker: true
